# TCL File Generated by Component Editor 23.1
# Wed Apr 02 12:29:52 CEST 2025
# DO NOT MODIFY


# 
# axi4lite_slave "axi4lite_slave" v1.0
#  2025.04.02.12:29:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module axi4lite_slave
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi4lite_slave
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axi4lite_slave
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi4lite_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi4lite_slave.vhd VHDL PATH ../src/axi4lite_slave.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AXI_DATA_WIDTH INTEGER 32
set_parameter_property AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property AXI_DATA_WIDTH DISPLAY_NAME AXI_DATA_WIDTH
set_parameter_property AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property AXI_DATA_WIDTH UNITS None
set_parameter_property AXI_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter AXI_ADDR_WIDTH INTEGER 12
set_parameter_property AXI_ADDR_WIDTH DEFAULT_VALUE 12
set_parameter_property AXI_ADDR_WIDTH DISPLAY_NAME AXI_ADDR_WIDTH
set_parameter_property AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property AXI_ADDR_WIDTH UNITS None
set_parameter_property AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock clock_sink
set_interface_property altera_axi4lite_slave associatedReset reset_sink
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave axi_araddr_i araddr Input "((axi_addr_width-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave axi_arprot_i arprot Input 3
add_interface_port altera_axi4lite_slave axi_arready_o arready Output 1
add_interface_port altera_axi4lite_slave axi_arvalid_i arvalid Input 1
add_interface_port altera_axi4lite_slave axi_awaddr_i awaddr Input "((axi_addr_width-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave axi_awprot_i awprot Input 3
add_interface_port altera_axi4lite_slave axi_awready_o awready Output 1
add_interface_port altera_axi4lite_slave axi_awvalid_i awvalid Input 1
add_interface_port altera_axi4lite_slave axi_bready_i bready Input 1
add_interface_port altera_axi4lite_slave axi_bresp_o bresp Output 2
add_interface_port altera_axi4lite_slave axi_bvalid_o bvalid Output 1
add_interface_port altera_axi4lite_slave axi_rdata_o rdata Output "((axi_data_width-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave axi_rready_i rready Input 1
add_interface_port altera_axi4lite_slave axi_rresp_o rresp Output 2
add_interface_port altera_axi4lite_slave axi_rvalid_o rvalid Output 1
add_interface_port altera_axi4lite_slave axi_wdata_i wdata Input "((axi_data_width-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave axi_wready_o wready Output 1
add_interface_port altera_axi4lite_slave axi_wstrb_i wstrb Input "(((axi_data_width/8)-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave axi_wvalid_i wvalid Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_i reset Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point external_connection
# 
add_interface external_connection conduit end
set_interface_property external_connection associatedClock clock_sink
set_interface_property external_connection associatedReset ""
set_interface_property external_connection ENABLED true
set_interface_property external_connection EXPORT_OF ""
set_interface_property external_connection PORT_NAME_MAP ""
set_interface_property external_connection CMSIS_SVD_VARIABLES ""
set_interface_property external_connection SVD_ADDRESS_GROUP ""

add_interface_port external_connection input_reg_A_i input_reg_a_i Input 32
add_interface_port external_connection input_reg_B_i input_reg_b_i Input 32
add_interface_port external_connection output_reg_A_o output_reg_a_o Output 32
add_interface_port external_connection output_reg_B_o output_reg_b_o Output 32
add_interface_port external_connection output_reg_C_o output_reg_c_o Output 32

